#!/usr/bin/env bash

# name: nginx.sh
# author: reagin
# github: https://github.com/reagin/resource
# description: install nginx for debian / ubuntu with a wildcard let's
#              encrypt certificate issued through the cloudflare dns plugin
#
# resulting layout (for the apex domain example.com):
#   /etc/letsencrypt/live/example.com/          certificate for example.com + *.example.com
#   /etc/nginx/nginx.conf                       default servers redirect to https://www.example.com
#   /etc/nginx/nginxconfig.io/{security,general}.conf
#   /etc/nginx/sites-available/@.example.com.conf        apex -> www redirect
#   /etc/nginx/sites-available/www.example.com.conf      static site, root /var/www/www.example.com/public
#   /etc/nginx/sites-available/<sub>.example.com.conf    reverse proxy subdomains
#   /etc/nginx/conf.d/<site>/*.conf             location snippets included by each site
#   /etc/nginx/sites-enabled/*.conf             symlinks to the enabled sites

# -E: err trap is inherited by functions, subshells and substitutions
# -e: exit immediately when a command fails
# -u: treat unset variables as an error
# -o pipefail: a pipeline fails when any of its commands fails
set -Eeuo pipefail

# base url of the shared libraries. override for local testing, e.g.
#   RESOURCE_LIB_BASE=file:///path/to/shellscript/library bash nginx.sh
RESOURCE_LIB_BASE="${RESOURCE_LIB_BASE:-https://raw.githubusercontent.com/reagin/resource/refs/heads/main/shellscript/library}"

command -v curl &>/dev/null || {
  printf '\x1B[38;2;215;0;0mError: curl is required, please install it first\x1B[0m\n' >&2
  exit 1
}
bootstrap_source=$(curl -fsSL "${RESOURCE_LIB_BASE}/bootstrap.lib.sh") || {
  printf '\x1B[38;2;215;0;0mError: failed to download %s/bootstrap.lib.sh\x1B[0m\n' "${RESOURCE_LIB_BASE}" >&2
  exit 1
}
eval "${bootstrap_source}"
unset bootstrap_source

setup_temp_directory
require_root
detect_environment
load_libraries message utility
ensure_commands openssl getent:libc-bin adduser:adduser systemctl:systemd

# -------------------------------------------------------------------
# global variables
# -------------------------------------------------------------------
readonly global_config_path='/etc/letsencrypt/cloudflare.ini'
readonly deploy_hook_path='/etc/letsencrypt/renewal-hooks/deploy/nginx-reload.sh'
readonly dhparam_path='/etc/nginx/dhparam.pem'
readonly sites_available='/etc/nginx/sites-available'
readonly sites_enabled='/etc/nginx/sites-enabled'
readonly snippets_root='/etc/nginx/conf.d'

declare user_email user_domain www_domain cloudflare_token
declare certificate_path certificate_key_path
declare http2_directive listen_http2

# -------------------------------------------------------------------
# configuration
# -------------------------------------------------------------------
generate_global_config() {
  cat <<EOF
# generated by nginx.sh, also used as certbot cloudflare credentials
user_email=${user_email}
user_domain=${user_domain}
dns_cloudflare_api_token=${cloudflare_token}
EOF
}

load_global_config() {
  if [[ -f "${global_config_path}" ]]; then
    show_info "loading configuration from ${global_config_path}\n"

    user_email=$(load_ini_config 'user_email' "${global_config_path}")
    user_domain=$(load_ini_config 'user_domain' "${global_config_path}")
    cloudflare_token=$(load_ini_config 'dns_cloudflare_api_token' "${global_config_path}")

    if [[ -z "${user_email}" || -z "${user_domain}" || -z "${cloudflare_token}" ]]; then
      show_error "configuration is incomplete, please repair or delete ${global_config_path}\n"
      return 1
    fi
  else
    show_info "please input your personal information as prompted\n"

    user_email=$(get_input_until_success "please input your email: " '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' "invalid email address")
    user_domain=$(get_input_until_success "please input your apex domain (e.g. example.com): " '^([a-z0-9-]+\.)+[a-z]{2,}$' "invalid domain name")
    cloudflare_token=$(get_input_until_success "please input your cloudflare api token: " '' '' true)

    install_content_with_comment 600 "root:root" "$(generate_global_config)" "${global_config_path}" true
  fi

  www_domain="www.${user_domain}"
  certificate_path="/etc/letsencrypt/live/${user_domain}/fullchain.pem"
  certificate_key_path="/etc/letsencrypt/live/${user_domain}/privkey.pem"
}

# -------------------------------------------------------------------
# certificate (apex + wildcard, shared by every site)
# -------------------------------------------------------------------
install_certbot() {
  if command -v certbot &>/dev/null && package_installed python3-certbot-dns-cloudflare; then
    show_info "certbot and the cloudflare dns plugin are already installed\n"
    return 0
  fi

  install_packages certbot python3-certbot-dns-cloudflare
  show_success "installed certbot and the cloudflare dns plugin\n"
}

certificate_covers_wildcard() {
  [[ -f "${certificate_path}" && -f "${certificate_key_path}" ]] || return 1
  openssl x509 -noout -ext subjectAltName -in "${certificate_path}" 2>/dev/null | grep -Fq "DNS:*.${user_domain}"
}

apply_domain_certificate() {
  local expand_flag=()

  if certificate_covers_wildcard; then
    show_info "certificate for ${user_domain} and *.${user_domain} already exists, skipping issuance\n"
    return 0
  fi

  [[ -f "${certificate_path}" ]] && expand_flag=(--expand)

  show_info "requesting certificate for ${user_domain} and *.${user_domain} via cloudflare dns challenge\n"
  certbot certonly --non-interactive --agree-tos --email "${user_email}" \
    --dns-cloudflare --dns-cloudflare-credentials "${global_config_path}" \
    --cert-name "${user_domain}" -d "${user_domain}" -d "*.${user_domain}" "${expand_flag[@]}" &>/dev/null || {
    show_error "certbot failed, please run manually: certbot certonly --dns-cloudflare --dns-cloudflare-credentials ${global_config_path} --email ${user_email} --cert-name ${user_domain} -d ${user_domain} -d '*.${user_domain}'\n"
    return 1
  }
  show_success "certificate saved under /etc/letsencrypt/live/${user_domain}\n"
}

generate_deploy_hook() {
  cat <<'EOF'
#!/bin/sh
# reload nginx after certbot renews a certificate
if systemctl is-active --quiet nginx.service; then
  systemctl reload nginx.service
fi
EOF
}

install_deploy_hook() {
  install_content_with_comment 755 "root:root" "$(generate_deploy_hook)" "${deploy_hook_path}" true
}

# -------------------------------------------------------------------
# nginx package, user and runtime facts
# -------------------------------------------------------------------
install_nginx() {
  if command -v nginx &>/dev/null; then
    show_info "nginx is already installed\n"
    return 0
  fi

  install_packages nginx
  show_success "installed nginx\n"
}

# create a dedicated nginx:nginx system account when it is missing.
# the distribution's www-data account is left untouched
ensure_nginx_user() {
  if getent passwd nginx &>/dev/null; then
    show_info "user nginx already exists\n"
  else
    show_info "creating system user and group nginx\n"
    adduser --system --group --home /var/www --no-create-home --shell /usr/sbin/nologin nginx &>/dev/null || {
      show_error "failed to create system user nginx\n"
      return 1
    }
    show_success "created system user and group nginx\n"
  fi

  # keep the logrotate configuration consistent with the running user
  if [[ -f /etc/logrotate.d/nginx ]] && grep -q 'www-data' /etc/logrotate.d/nginx; then
    show_info "updating /etc/logrotate.d/nginx to create logs owned by nginx\n"
    sed -Ei 's/\bwww-data\b/nginx/g' /etc/logrotate.d/nginx
  fi
}

# the standalone "http2 on;" directive only exists since nginx 1.25.1,
# older packages (debian 12: 1.22, ubuntu 24.04: 1.24) need "listen ... http2"
detect_http2_directive() {
  local version lowest

  version=$(nginx -v 2>&1 | sed -En 's|.*nginx/([0-9]+(\.[0-9]+)*).*|\1|p')
  lowest=$(printf '%s\n' "1.25.1" "${version:-0}" | sort -V | head -n 1)

  if [[ "${lowest}" == "1.25.1" ]]; then
    http2_directive="http2 on;"
    listen_http2=""
  else
    http2_directive=""
    listen_http2=" http2"
  fi
  show_info "nginx version ${version:-unknown}, http/2 enabled via ${http2_directive:-listen parameter}\n"
}

ensure_dhparam() {
  if [[ -f "${dhparam_path}" ]] && openssl dhparam -check -in "${dhparam_path}" &>/dev/null; then
    show_info "valid diffie-hellman parameters already exist at ${dhparam_path}\n"
    return 0
  fi

  show_info "generating diffie-hellman parameters at ${dhparam_path} (this may take a while)\n"
  openssl dhparam -out "${dhparam_path}" 2048 &>/dev/null || {
    show_error "failed to generate diffie-hellman parameters\n"
    return 1
  }
  show_success "generated diffie-hellman parameters\n"
}

# -------------------------------------------------------------------
# nginx configuration files
# -------------------------------------------------------------------
generate_nginx_conf() {
  cat <<EOF
user                 nginx;
pid                  /run/nginx.pid;
worker_processes     auto;
worker_rlimit_nofile 65535;

# Load modules
include              /etc/nginx/modules-enabled/*.conf;

events {
    multi_accept       on;
    worker_connections 65535;
}

http {
    charset                utf-8;
    sendfile               on;
    tcp_nopush             on;
    tcp_nodelay            on;
    server_tokens          off;
    log_not_found          off;
    types_hash_max_size    2048;
    types_hash_bucket_size 64;
    client_max_body_size   0;

    # MIME
    include                mime.types;
    default_type           application/octet-stream;

    # Logging
    access_log             off;
    error_log              /dev/null;

    # SSL
    ssl_session_timeout    1d;
    ssl_session_cache      shared:SSL:10m;
    ssl_session_tickets    off;

    # diffie-hellman parameter for DHE ciphersuites
    ssl_dhparam            ${dhparam_path};

    # Mozilla Intermediate configuration
    ssl_protocols          TLSv1.2 TLSv1.3;
    ssl_ciphers            ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    # OCSP Stapling
    ssl_stapling           off;
    ssl_stapling_verify    off;
    resolver               1.1.1.1 8.8.8.8 valid=60s;
    resolver_timeout       2s;

    # Define server location conf map
    map \$http_upgrade \$connection_upgrade {
        default upgrade;
        ''      close;
    }

    # Define default server below
    server {
        listen 80 default_server;
        server_name _;

        return 301 https://${www_domain}\$request_uri;
    }

    server {
        listen 443 ssl${listen_http2} default_server;
        server_name _;

        ${http2_directive}

        ssl_certificate     ${certificate_path};
        ssl_certificate_key ${certificate_key_path};

        # security
        include             nginxconfig.io/security.conf;

        # logging
        access_log          /var/log/nginx/access.log combined buffer=512k flush=1m;
        error_log           /var/log/nginx/error.log warn;

        # additional config
        include             nginxconfig.io/general.conf;

        return 301 https://${www_domain}\$request_uri;
    }

    # Load configs
    include                ${snippets_root}/*.conf;
    include                ${sites_enabled}/*;
}
EOF
}

# apex domain: redirect everything to the www site
generate_apex_conf() {
  cat <<EOF
# HTTP redirect
server {
    listen      80;
    server_name ${user_domain};
    return      301 https://${www_domain}\$request_uri;
}

server {
    listen              443 ssl${listen_http2};
    server_name         ${user_domain};

    ${http2_directive}

    # SSL
    ssl_certificate     ${certificate_path};
    ssl_certificate_key ${certificate_key_path};

    return              301 https://${www_domain}\$request_uri;
}
EOF
}

# www site: static root plus location snippets from conf.d/www.<domain>/
generate_www_conf() {
  cat <<EOF
# HTTP redirect
server {
    listen      80;
    server_name ${www_domain};
    return      301 https://${www_domain}\$request_uri;
}

server {
    listen              443 ssl${listen_http2};
    server_name         ${www_domain};
    root                /var/www/${www_domain}/public;

    ${http2_directive}

    # SSL
    ssl_certificate     ${certificate_path};
    ssl_certificate_key ${certificate_key_path};

    # additional location config
    include             ${snippets_root}/${www_domain}/*.conf;
}
EOF
}

# subdomain site: all locations come from conf.d/<sub>.<domain>/
generate_proxy_site_conf() {
  local site="${1}"

  cat <<EOF
# HTTP redirect
server {
    listen      80;
    server_name ${site};
    return      301 https://${site}\$request_uri;
}

server {
    listen              443 ssl${listen_http2};
    server_name         ${site};

    ${http2_directive}

    # SSL
    ssl_certificate     ${certificate_path};
    ssl_certificate_key ${certificate_key_path};

    # additional location config
    include             ${snippets_root}/${site}/*.conf;
}
EOF
}

# conf.d/<site>/@.conf: proxy the whole site to a local port
generate_proxy_location_conf() {
  local port="${1}"

  cat <<EOF
location / {
    proxy_pass http://127.0.0.1:${port};

    proxy_http_version 1.1;

    proxy_set_header Host \$host;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \$connection_upgrade;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;
}
EOF
}

generate_security_conf() {
  cat <<'EOF'
# security headers
add_header X-XSS-Protection          "1; mode=block" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
add_header Permissions-Policy        "interest-cohort=()" always;
add_header Content-Security-Policy   "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'; frame-ancestors 'self';" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# . files
location ~ /\.(?!well-known) {
    deny all;
}
EOF
}

generate_general_conf() {
  cat <<'EOF'
# favicon.ico
location = /favicon.ico {
    log_not_found off;
}

# robots.txt
location = /robots.txt {
    log_not_found off;
}

# assets, media
location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
    expires 7d;
}

# svg, fonts
location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
    add_header Access-Control-Allow-Origin "*";
    expires    7d;
}

# gzip
gzip            on;
gzip_vary       on;
gzip_proxied    any;
gzip_comp_level 6;
gzip_types      text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
EOF
}

generate_index_html() {
  cat <<'EOF'
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to NGINX</title>
    <style>
      body {
        margin: 0;
        background-color: #0f172a;
        font-family: system-ui, sans-serif;
        color: #e2e8f0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        text-align: center;
      }
      h1 {
        font-size: 3rem;
        margin-bottom: 0.5rem;
      }
      p {
        color: #94a3b8;
        font-size: 1.1rem;
      }
      a {
        color: #38bdf8;
        text-decoration: none;
      }
      .badge {
        margin-top: 1rem;
        display: inline-block;
        padding: 0.4rem 1rem;
        background-color: #1e293b;
        border-radius: 9999px;
        font-size: 0.9rem;
        color: #38bdf8;
      }
    </style>
  </head>
  <body>
    <h1>Welcome to NGINX</h1>
    <p>If you see this page, the NGINX web server is successfully installed and working.</p>
    <div class="badge">Server Ready</div>
    <p><a href="https://nginx.org" target="_blank">Learn more at nginx.org</a></p>
  </body>
</html>
EOF
}

# -------------------------------------------------------------------
# site management
# -------------------------------------------------------------------
enable_site() {
  local site="${1}"

  show_info "enabling site ${site}\n"
  ln -sfn "${sites_available}/${site}.conf" "${sites_enabled}/${site}.conf"
}

# create a reverse proxy site <sub>.<domain> -> 127.0.0.1:<port>
add_proxy_site() {
  local sub="${1}" port="${2}" site

  site="${sub}.${user_domain}"

  if [[ -f "${sites_available}/${site}.conf" ]]; then
    show_warn "site ${site} already exists, leaving its configuration untouched\n"
    return 0
  fi

  install_content_with_comment 644 "root:root" "$(generate_proxy_site_conf "${site}")" "${sites_available}/${site}.conf" true
  install_content_with_comment 644 "root:root" "$(generate_proxy_location_conf "${port}")" "${snippets_root}/${site}/@.conf" true
  enable_site "${site}"
}

write_nginx_configs() {
  install -dm755 "${sites_available}" "${sites_enabled}" "${snippets_root}/${www_domain}"

  install_content_with_comment 644 "root:root" "$(generate_nginx_conf)" "/etc/nginx/nginx.conf" true
  install_content_with_comment 644 "root:root" "$(generate_security_conf)" "/etc/nginx/nginxconfig.io/security.conf" true
  install_content_with_comment 644 "root:root" "$(generate_general_conf)" "/etc/nginx/nginxconfig.io/general.conf" true
  install_content_with_comment 644 "root:root" "$(generate_apex_conf)" "${sites_available}/@.${user_domain}.conf" true
  install_content_with_comment 644 "root:root" "$(generate_www_conf)" "${sites_available}/${www_domain}.conf" true

  if [[ ! -f "/var/www/${www_domain}/public/index.html" ]]; then
    install_content_with_comment 644 "root:root" "$(generate_index_html)" "/var/www/${www_domain}/public/index.html" true
  fi

  # the distribution's default site also claims default_server on port 80.
  # the enabled link is what nginx loads; the sites-available file is unused
  # once this script's catch-all servers are in place, so drop both
  remove_content_with_comment "${sites_enabled}/default"
  remove_content_with_comment "${sites_available}/default"

  enable_site "@.${user_domain}"
  enable_site "${www_domain}"
}

# interactively add reverse proxy subdomains, empty input finishes the loop
configure_proxy_sites() {
  local sub port

  echo
  show_info "you can now add reverse proxy subdomains (<sub>.${user_domain} -> 127.0.0.1:<port>)\n"

  # empty input (or end of input when running non-interactively) finishes the loop
  while true; do
    sub=$(get_input_message "subdomain to add (e.g. casaos), leave empty to finish: ")
    sub="${sub,,}"
    [[ -n "${sub}" ]] || break

    if ! grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$' <<<"${sub}"; then
      show_warn "invalid subdomain label: ${sub}\n"
      continue
    fi
    if [[ "${sub}" == "www" ]]; then
      show_warn "www.${user_domain} is the static site managed by this script\n"
      continue
    fi

    port=$(get_input_until_success "upstream port for ${sub}.${user_domain}: " '^[0-9]{1,5}$' "port must be a number")
    if ((10#${port} < 1 || 10#${port} > 65535)); then
      show_warn "port out of range: ${port}\n"
      continue
    fi

    add_proxy_site "${sub}" "${port}"
  done
}

reload_nginx() {
  local test_output

  show_info "validating nginx configuration\n"
  if ! test_output=$(nginx -t 2>&1); then
    show_error "nginx configuration test failed:\n${test_output}\n"
    return 1
  fi

  systemctl enable nginx.service &>/dev/null || true

  if systemctl is-active --quiet nginx.service; then
    show_info "reloading nginx.service\n"
    systemctl reload nginx.service || {
      show_error "failed to reload nginx.service, check: journalctl -u nginx.service\n"
      return 1
    }
    show_success "reloaded nginx.service\n"
  else
    show_info "starting nginx.service\n"
    systemctl start nginx.service || {
      show_error "failed to start nginx.service, check: journalctl -u nginx.service\n"
      return 1
    }
    show_success "started nginx.service\n"
  fi
}

print_summary() {
  echo
  show_success "nginx is serving https://${www_domain} from /var/www/${www_domain}/public\n"
  show_info "layout:\n"
  show_text "    ${sites_available}/<site>.conf          server blocks (enable with: ln -s into ${sites_enabled}/)\n"
  show_text "    ${snippets_root}/<site>/*.conf          location snippets included by each site\n"
  show_text "    ${snippets_root}/<sub>.${user_domain}/@.conf   whole-site reverse proxy created by this script\n"
  show_info "add another proxy subdomain by re-running this script, or copy an existing site pair by hand\n"
  show_info "disable a site with: rm ${sites_enabled}/<site>.conf && nginx -t && systemctl reload nginx\n"
}

# -------------------------------------------------------------------
# main program entry
# -------------------------------------------------------------------
load_global_config
install_certbot
apply_domain_certificate
install_deploy_hook
install_nginx
ensure_nginx_user
detect_http2_directive
ensure_dhparam
write_nginx_configs
configure_proxy_sites
reload_nginx
print_summary
